version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    env_file:
      - .env